In [139]:
import nltk
from sklearn.metrics import classification_report, r2_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
import torch
import torch.nn as nn

#from torch_model_base import TorchModelBase
#from torch_shallow_neural_classifier import TorchShallowNeuralClassifier
from torch_rnn_classifier import TorchRNNDataset, TorchRNNClassifier, TorchRNNModel
import utils

import pandas as pd
from collections import Counter

In [140]:
# refresh torch rnn classifier:
import importlib
import torch_rnn_classifier
importlib.reload(torch_rnn_classifier)
from torch_rnn_classifier import TorchRNNDataset

In [3]:
import json

In [4]:
with open('annotations2.jsonl') as jsonl_file:
    # note: after running data-preprocessing.ipynb this file already has token-level labels
    lines = jsonl_file.readlines()
annot = [json.loads(line) for line in lines]

In [5]:
# now get data into format that TorchRNN expects:
X=[] 
y=[]
for j in range(0,len(annot)):
    a = annot[j]['tokens']
    auxX = []
    auxy = []
    if annot[j]['spans']!=[]: # are there annot for this example?
        for i in range(0,len(a)):
            #token_element = (a[i]['text'],a[i]['label'])
            auxX.append(a[i]['text'])
            auxy.append(a[i]['label'])
        X.append(auxX)
        y.append(auxy)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
X_train, X_test, y_train, y_test = X[:120], X[120:], y[:120], y[120:]
vocab = sorted({w for seq in X_train for w in seq}) + ["$UNK"]

In [221]:
# reload vsm module
import torch_rnn_classifier, torch_model_base
import importlib
importlib.reload(torch_model_base)
importlib.reload(torch_rnn_classifier)
from torch_model_base import TorchModelBase
from torch_rnn_classifier import TorchRNNClassifier, TorchRNNModel, TorchRNNDataset

In [222]:
class TorchRNNSequenceLabeler(TorchRNNClassifier):

    def build_graph(self): # uses this build_graph instead of TorchRNNClassifier.build_graph
        print("here0")
        rnn = TorchRNNModel(
            vocab_size=len(self.vocab),
            embedding=self.embedding,
            use_embedding=self.use_embedding,
            embed_dim=self.embed_dim,
            rnn_cell_class=self.rnn_cell_class,
            hidden_dim=self.hidden_dim,
            bidirectional=self.bidirectional,
            freeze_embedding=self.freeze_embedding)
        print("here02")
        model = TorchSequenceLabeler( # this defines self.model
            rnn=rnn,
            output_dim=self.n_classes_)
        self.embed_dim = rnn.embed_dim
        return model

    def build_dataset(self, X, y=None):
        START_TAG = "<START>"
        STOP_TAG = "<STOP>"
        X, seq_lengths = self._prepare_sequences(X) # converts tokens into tokenIds
        if y is None:
            return TorchRNNDataset(X, seq_lengths)
        else:
            # These are the changes from a regular classifier. All
            # concern the fact that our labels are sequences of labels.
            self.classes_ = sorted({x for seq in y for x in seq})
            self.n_classes_ = len(self.classes_)
            class2index = dict(zip(self.classes_, range(self.n_classes_)))
            # `y` is a list of tensors of different length. Our Dataset
            # class will turn it into a padding tensor for processing.
            y = [torch.tensor([class2index[label] for label in seq])
                 for seq in y] # converts labels to indices
            return TorchRNNDataset(X, seq_lengths, y)

    def predict_proba(self, X):
        seq_lengths = [len(ex) for ex in X]
        # The base class does the heavy lifting:
        preds = self._predict(X)
        # Trim to the actual sequence lengths:
        preds = [p[: l] for p, l in zip(preds, seq_lengths)]
        # Use `softmax`; the model doesn't do this because the loss
        # function does it internally.
        probs = [torch.softmax(seq, dim=1) for seq in preds]
        return probs

    def predict(self, X): #out: list of lists with text labels of predictions
        probs = self.predict_proba(X)
        return [[self.classes_[i] for i in seq.argmax(axis=1)] for seq in probs] # seq.argmax(axis=1) gives index of col that maximizes softmax prob
        # see difference vs TorchRNNClassifier.predict

    def score(self, X, y):
        preds = self.predict(X)
        flat_preds = [x for seq in preds for x in seq]
        flat_y = [x for seq in y for x in seq]
        return utils.safe_macro_f1(flat_y, flat_preds)
    

    
    
class TorchSequenceLabeler(nn.Module): # no self.hidden_layer or self.classifier_activation as TorchRNNClassifierModel
    def __init__(self, rnn, output_dim):
        print("here021")
        super().__init__()
        self.rnn = rnn
        self.output_dim = output_dim
        if self.rnn.bidirectional:
            self.classifier_dim = self.rnn.hidden_dim * 2
        else:
            self.classifier_dim = self.rnn.hidden_dim
        self.classifier_layer = nn.Linear(
            self.classifier_dim, self.output_dim)

    def forward(self, X, seq_lengths): # X is (noExsInBatch,MaxLen)=(108,117), seq_lengths is the number of tokens in each example in each batch
        # Out are logits - probs of each token for each class; logits are (108,117,12) or (1,11,5) = (batchSize,MaxLen of examples in batch,noLabelClasses) noLabelClasses include Start + End
        # this is the forward method of self.model
        print("here2")
        print(type(X))
        print(type(seq_lengths))
        outputs, state = self.rnn(X, seq_lengths) # X is (batchSize, maxLen of exs in batch); outputs is (noTokensInEx,hiddDim), state is ((batch_size,1,hiddDim),(batch_size,1,hiddDim)) = (finalHiddState,finalCellState) 
       # print("out1")
        print(outputs.data.shape)
        #print(state[0].data.shape)
        #print(state[1].data.shape)
        outputs, seq_length = torch.nn.utils.rnn.pad_packed_sequence(
            outputs, batch_first=True) # outputs is (batchSize,MaxLen of examples in batch,hidden_dim); seq_length is noTokenInEx for each ex in batch
       # print("out2")
        print(outputs.data.shape)
        #print(seq_length)
        logits = self.classifier_layer(outputs) # this is an FCL from hidden_dim to output_dim (NoLabelClasses)
        # During training, we need to swap the dimensions of logits
        # to accommodate `nn.CrossEntropyLoss`:
        print(logits)
        if self.training:
            return logits.transpose(1, 2) # transpose dimensions 1 and 2 w/ each other (3d array) # outputs (108,12,117) or (1,5,11)
        else:
            return logits

In [6]:
X_train = ["the wall street journal reported today that apple corporation made money".split(),"georgia tech is a university in georgia".split()]
y_train = ["B I I I O O O B I O O".split(),"B I O O O O B".split()]
vocab = sorted({w for seq in X_train for w in seq}) + ["$UNK"]

In [223]:
seq_mod = TorchRNNSequenceLabeler(
    vocab,
    early_stopping=True,
    eta=0.001)

In [187]:
graph0 = seq_mod.build_graph()
print(graph0)

here0
here01
here02
here021
TorchSequenceLabeler(
  (rnn): TorchRNNModel(
    (embedding): Embedding(1049, 50)
    (rnn): LSTM(50, 50, batch_first=True)
  )
  (classifier_layer): Linear(in_features=50, out_features=12, bias=True)
)


In [224]:
%time _ = seq_mod.fit(X_train, y_train)

Finished epoch 2 of 1000; error is 2.4679622650146484

here00
here0
here01
here02
here021
batch1
here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([5845, 50])
torch.Size([108, 117, 50])
tensor([[[ 0.1555,  0.1656,  0.1929,  ..., -0.0701,  0.0507,  0.0170],
         [ 0.2475,  0.0425,  0.1348,  ..., -0.0693, -0.0505, -0.0182],
         [ 0.2581,  0.2185,  0.0750,  ..., -0.0397,  0.0245,  0.0540],
         ...,
         [ 0.1307,  0.0677,  0.1158,  ..., -0.0671,  0.1205, -0.0135],
         [ 0.1307,  0.0677,  0.1158,  ..., -0.0671,  0.1205, -0.0135],
         [ 0.1307,  0.0677,  0.1158,  ..., -0.0671,  0.1205, -0.0135]],

        [[ 0.0744,  0.0264,  0.1459,  ..., -0.0602,  0.0489, -0.0761],
         [ 0.0421, -0.1507,  0.1405,  ..., -0.0403,  0.0051, -0.0264],
         [ 0.0792, -0.0927,  0.1270,  ..., -0.0051,  0.0446,  0.0004],
         ...,
         [ 0.1307,  0.0677,  0.1158,  ..., -0.0671,  0.1205, -0.0135],
         [ 0.1307,  0.0677,  0.1158,  ..., -0.0671,  0.1205, -0.0135],
         [ 0.1307,  0.0677,  0.1158,  

Finished epoch 4 of 1000; error is 2.4458308219909672

batch1
here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([5845, 50])
torch.Size([108, 117, 50])
tensor([[[ 0.2124,  0.0701,  0.1721,  ...,  0.0012,  0.1832,  0.0602],
         [ 0.0900, -0.1026,  0.1534,  ..., -0.0363,  0.0799,  0.0096],
         [ 0.0618, -0.0185,  0.1198,  ..., -0.1365,  0.0970, -0.1287],
         ...,
         [ 0.1327,  0.0657,  0.1138,  ..., -0.0691,  0.1185, -0.0155],
         [ 0.1327,  0.0657,  0.1138,  ..., -0.0691,  0.1185, -0.0155],
         [ 0.1327,  0.0657,  0.1138,  ..., -0.0691,  0.1185, -0.0155]],

        [[ 0.0958,  0.0801,  0.0630,  ..., -0.0561,  0.0423, -0.0704],
         [ 0.0240,  0.0920,  0.1473,  ..., -0.0960,  0.2591, -0.1204],
         [-0.0210,  0.0704,  0.1762,  ..., -0.1205,  0.3610, -0.1504],
         ...,
         [ 0.1327,  0.0657,  0.1138,  ..., -0.0691,  0.1185, -0.0155],
         [ 0.1327,  0.0657,  0.1138,  ..., -0.0691,  0.1185, -0.0155],
         [ 0.1327,  0.0657,  0.1138,  ..., -0.0691,  0.1185, -0.0155]],



Finished epoch 6 of 1000; error is 2.4237730503082275

torch.Size([696, 50])
torch.Size([12, 87, 50])
tensor([[[ 6.4161e-02, -5.6284e-02, -2.8749e-02,  ..., -1.3859e-01,
           2.3736e-02, -1.3168e-01],
         [ 9.1779e-02, -1.0776e-02, -7.3187e-02,  ..., -1.6277e-01,
          -5.2684e-02, -1.3148e-01],
         [ 1.5702e-01,  4.6549e-02, -5.1470e-02,  ..., -8.2120e-02,
           3.4676e-03, -2.7178e-01],
         ...,
         [ 9.5034e-02,  5.0870e-02,  1.4430e-01,  ..., -7.5742e-02,
           2.4008e-01,  9.8319e-02],
         [ 1.9529e-01,  8.2651e-03,  4.9915e-02,  ...,  3.2913e-02,
           1.7206e-01,  9.3258e-02],
         [ 1.1054e-01,  5.3191e-02,  5.5372e-02,  ..., -5.1415e-02,
           5.1349e-02, -2.3098e-03]],

        [[ 1.8423e-01,  1.4590e-01,  7.6264e-02,  ..., -1.2069e-01,
           9.4881e-02, -6.7345e-02],
         [ 3.4063e-02,  6.7193e-02,  1.3158e-01,  ..., -1.4428e-01,
           2.6157e-01, -8.6309e-02],
         [ 4.6893e-02,  1.2708e-01,  9.3888e-02,  ..., -2.2537e-01,
           2.4153e-01, -1.248

Finished epoch 9 of 1000; error is 2.3894722461700445

batch1
here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([5845, 50])
torch.Size([108, 117, 50])
tensor([[[ 1.8452e-01,  1.4182e-01,  7.3143e-02,  ..., -1.2275e-01,
           9.2368e-02, -6.8833e-02],
         [ 2.9445e-02,  5.9562e-02,  1.2166e-01,  ..., -1.5064e-01,
           2.5387e-01, -9.6135e-02],
         [ 5.7529e-02,  6.8543e-02,  9.6782e-02,  ..., -1.3153e-01,
           9.9517e-02, -4.0871e-02],
         ...,
         [ 1.3772e-01,  6.0736e-02,  1.0881e-01,  ..., -7.4115e-02,
           1.1346e-01, -2.0464e-02],
         [ 1.3772e-01,  6.0736e-02,  1.0881e-01,  ..., -7.4115e-02,
           1.1346e-01, -2.0464e-02],
         [ 1.3772e-01,  6.0736e-02,  1.0881e-01,  ..., -7.4115e-02,
           1.1346e-01, -2.0464e-02]],

        [[ 1.2868e-01,  1.0296e-01,  7.6515e-02,  ..., -1.6763e-01,
           1.7179e-02, -1.1325e-01],
         [ 3.7162e-02,  6.9748e-02,  1.0870e-01,  ..., -1.6555e-01,
           2.2432e-01, -1.6905e-01],
         [ 2.7673e-04, -4.15

Finished epoch 11 of 1000; error is 2.364762306213379

here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([696, 50])
torch.Size([12, 87, 50])
tensor([[[ 0.0540, -0.0688, -0.0571,  ..., -0.1451,  0.0059, -0.1418],
         [ 0.0607, -0.0248, -0.1253,  ..., -0.1874, -0.0750, -0.1591],
         [ 0.1303,  0.0311, -0.1148,  ..., -0.1085, -0.0398, -0.3057],
         ...,
         [ 0.0986,  0.0603,  0.1378,  ..., -0.0777,  0.2248,  0.1097],
         [ 0.1890,  0.0100,  0.0415,  ...,  0.0223,  0.1658,  0.0902],
         [ 0.0238,  0.0349, -0.0178,  ..., -0.1155,  0.0170, -0.0380]],

        [[ 0.1846,  0.1355,  0.0686,  ..., -0.1256,  0.0896, -0.0708],
         [ 0.0221,  0.0472,  0.1054,  ..., -0.1597,  0.2414, -0.1118],
         [ 0.0389,  0.1162,  0.0718,  ..., -0.2339,  0.2206, -0.1424],
         ...,
         [ 0.1407,  0.0577,  0.1058,  ..., -0.0771,  0.1105, -0.0235],
         [ 0.1407,  0.0577,  0.1058,  ..., -0.0771,  0.1105, -0.0235],
         [ 0.1407,  0.0577,  0.1058,  ..., -0.0771,  0.1105, -0.0235]],

        [[

Finished epoch 14 of 1000; error is 2.3229446411132812

batch1
here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([5845, 50])
torch.Size([108, 117, 50])
tensor([[[ 5.4391e-02,  3.7600e-04,  9.1879e-02,  ..., -7.5653e-02,
           1.2963e-01,  9.5066e-03],
         [ 6.1779e-02, -1.3293e-01,  1.8807e-01,  ..., -4.4079e-02,
           7.1898e-02,  4.6665e-02],
         [ 2.7412e-02, -5.7628e-02,  1.0297e-01,  ..., -1.4382e-01,
           5.9479e-02, -1.3429e-01],
         ...,
         [ 1.4272e-01,  5.5740e-02,  1.0383e-01,  ..., -7.9106e-02,
           1.0846e-01, -2.5463e-02],
         [ 1.4272e-01,  5.5740e-02,  1.0383e-01,  ..., -7.9106e-02,
           1.0846e-01, -2.5463e-02],
         [ 1.4272e-01,  5.5740e-02,  1.0383e-01,  ..., -7.9106e-02,
           1.0846e-01, -2.5463e-02]],

        [[ 8.6041e-02, -5.6845e-02,  1.2363e-02,  ..., -1.6382e-01,
           1.0753e-01, -1.3191e-02],
         [-3.7191e-02,  1.7909e-04,  7.9963e-02,  ..., -2.0401e-01,
           2.8886e-01, -1.4505e-01],
         [-1.6861e-02, -1.03

Finished epoch 16 of 1000; error is 2.2905476093292236

here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([696, 50])
torch.Size([12, 87, 50])
tensor([[[ 3.6935e-02, -8.9291e-02, -9.2264e-02,  ..., -1.5452e-01,
          -1.8519e-02, -1.5753e-01],
         [ 1.5075e-02, -5.7132e-02, -1.9795e-01,  ..., -2.2015e-01,
          -1.1495e-01, -2.0061e-01],
         [ 8.9381e-02,  1.0569e-04, -1.9848e-01,  ..., -1.3754e-01,
          -1.0106e-01, -3.5624e-01],
         ...,
         [ 9.8998e-02,  6.7860e-02,  1.3036e-01,  ..., -8.2296e-02,
           2.0921e-01,  1.1865e-01],
         [ 1.8071e-01,  8.1660e-03,  2.7506e-02,  ...,  1.1176e-02,
           1.5635e-01,  8.5135e-02],
         [-7.7729e-02, -8.8890e-03, -1.2531e-01,  ..., -1.8216e-01,
          -3.3859e-02, -8.9988e-02]],

        [[ 1.8430e-01,  1.2534e-01,  6.1069e-02,  ..., -1.3039e-01,
           8.5813e-02, -7.4160e-02],
         [ 7.2360e-03,  2.3925e-02,  7.5151e-02,  ..., -1.7587e-01,
           2.1792e-01, -1.4067e-01],
         [ 2.3876e-02,  9.9736e-02,  4

Finished epoch 19 of 1000; error is 2.2324211597442627

batch1
here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([5845, 50])
torch.Size([108, 117, 50])
tensor([[[ 0.0894, -0.0281,  0.0055,  ..., -0.0870,  0.1478, -0.0553],
         [-0.0727, -0.0203,  0.0376,  ..., -0.1646,  0.2466, -0.1788],
         [-0.1792, -0.1255, -0.0844,  ..., -0.1365,  0.2729, -0.2025],
         ...,
         [ 0.1477,  0.0508,  0.0989,  ..., -0.0841,  0.1035, -0.0305],
         [ 0.1477,  0.0508,  0.0989,  ..., -0.0841,  0.1035, -0.0305],
         [ 0.1477,  0.0508,  0.0989,  ..., -0.0841,  0.1035, -0.0305]],

        [[ 0.0552, -0.0081,  0.0804,  ..., -0.0868,  0.1204, -0.0025],
         [-0.0482, -0.0192,  0.0870,  ..., -0.1370,  0.2365, -0.1351],
         [-0.1511, -0.1229, -0.0562,  ..., -0.1133,  0.2943, -0.1799],
         ...,
         [ 0.1477,  0.0508,  0.0989,  ..., -0.0841,  0.1035, -0.0305],
         [ 0.1477,  0.0508,  0.0989,  ..., -0.0841,  0.1035, -0.0305],
         [ 0.1477,  0.0508,  0.0989,  ..., -0.0841,  0.1035, -0.0305]],



Finished epoch 22 of 1000; error is 2.1591637134552527

here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([696, 50])
torch.Size([12, 87, 50])
tensor([[[ 0.0111, -0.1193, -0.1372,  ..., -0.1704, -0.0522, -0.1826],
         [-0.0498, -0.1108, -0.2985,  ..., -0.2672, -0.1786, -0.2649],
         [ 0.0246, -0.0543, -0.3185,  ..., -0.1802, -0.1942, -0.4348],
         ...,
         [ 0.0916,  0.0675,  0.1136,  ..., -0.0892,  0.1911,  0.1226],
         [ 0.1675, -0.0028,  0.0034,  ..., -0.0010,  0.1421,  0.0780],
         [-0.2034, -0.0881, -0.2776,  ..., -0.2628, -0.1141, -0.1720]],

        [[ 0.1841,  0.1173,  0.0534,  ..., -0.1360,  0.0821, -0.0787],
         [-0.0120, -0.0014,  0.0410,  ..., -0.1964,  0.1923, -0.1726],
         [-0.0008,  0.0766,  0.0033,  ..., -0.2658,  0.1618, -0.2033],
         ...,
         [ 0.1507,  0.0478,  0.0959,  ..., -0.0871,  0.1005, -0.0335],
         [ 0.1507,  0.0478,  0.0959,  ..., -0.0871,  0.1005, -0.0335],
         [ 0.1507,  0.0478,  0.0959,  ..., -0.0871,  0.1005, -0.0335]],

        [[

Finished epoch 24 of 1000; error is 2.1003589630126953

batch1
here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([5845, 50])
torch.Size([108, 117, 50])
tensor([[[ 0.0933,  0.0554, -0.0139,  ..., -0.2128,  0.0131, -0.1764],
         [ 0.1057, -0.1001,  0.1148,  ..., -0.1037,  0.0550, -0.0326],
         [-0.0263, -0.1263, -0.0120,  ..., -0.1936, -0.0303, -0.2343],
         ...,
         [ 0.1527,  0.0458,  0.0940,  ..., -0.0891,  0.0985, -0.0354],
         [ 0.1527,  0.0458,  0.0940,  ..., -0.0891,  0.0985, -0.0354],
         [ 0.1527,  0.0458,  0.0940,  ..., -0.0891,  0.0985, -0.0354]],

        [[ 0.1841,  0.1148,  0.0501,  ..., -0.1386,  0.0807, -0.0812],
         [ 0.1610, -0.0634,  0.1598,  ..., -0.0724,  0.0796,  0.0087],
         [ 0.0172, -0.1027,  0.0228,  ..., -0.1739, -0.0063, -0.2104],
         ...,
         [ 0.1527,  0.0458,  0.0940,  ..., -0.0891,  0.0985, -0.0354],
         [ 0.1527,  0.0458,  0.0940,  ..., -0.0891,  0.0985, -0.0354],
         [ 0.1527,  0.0458,  0.0940,  ..., -0.0891,  0.0985, -0.0354]],



Stopping after epoch 26. Validation score did not improve by tol=1e-05 for more than 10 epochs. Final error is 2.0340569019317627

here2
<class 'torch.Tensor'>
<class 'torch.Tensor'>
here21
torch.Size([696, 50])
torch.Size([12, 87, 50])
tensor([[[-0.0242, -0.1574, -0.1952,  ..., -0.1959, -0.0974, -0.2202],
         [-0.1395, -0.1865, -0.4355,  ..., -0.3351, -0.2713, -0.3599],
         [-0.0764, -0.1414, -0.4907,  ..., -0.2499, -0.3338, -0.5524],
         ...,
         [ 0.0557,  0.0420,  0.0617,  ..., -0.1075,  0.1613,  0.1125],
         [ 0.1334, -0.0393, -0.0536,  ..., -0.0218,  0.1132,  0.0640],
         [-0.3712, -0.2177, -0.4972,  ..., -0.3713, -0.2396, -0.2994]],

        [[ 0.1837,  0.1116,  0.0450,  ..., -0.1430,  0.0782, -0.0856],
         [-0.0379, -0.0294,  0.0011,  ..., -0.2236,  0.1636, -0.2101],
         [-0.0387,  0.0440, -0.0472,  ..., -0.2976,  0.1216, -0.2484],
         ...,
         [ 0.1557,  0.0428,  0.0911,  ..., -0.0920,  0.0956, -0.0384],
         [ 0.1557,  0.0428,  0.0911,  ..., -0.0920,  0.0956, -0.0384],
         [ 0.1557,  0.0428,  0.0911,  ..., -0.0920,  0.0956, -0.0384]],

        [[

In [3]:
# reload vsm module
import torch_rnn_classifier, torch_model_base
import importlib
importlib.reload(torch_model_base)
importlib.reload(torch_rnn_classifier)
from torch_model_base import TorchModelBase
from torch_rnn_classifier import TorchRNNClassifier, TorchRNNModel, TorchRNNDataset

In [102]:
from torchcrf import CRF

class TorchCRFSequenceLabeler_1(TorchRNNClassifier):

    def build_graph(self): # uses this build_graph instead of TorchRNNClassifier.build_graph
        print("here0")
        rnn = TorchRNNModel(
            vocab_size=len(self.vocab),
            embedding=self.embedding,
            use_embedding=self.use_embedding,
            embed_dim=self.embed_dim,
            rnn_cell_class=self.rnn_cell_class,
            hidden_dim=self.hidden_dim,
            bidirectional=self.bidirectional,
            freeze_embedding=self.freeze_embedding)
        print("here02")
        model = TorchSequenceLabeler_forCRF_1( # this defines self.model
            rnn=rnn,
            output_dim=self.n_classes_)
        self.embed_dim = rnn.embed_dim
        return model

    def build_dataset(self, X, y=None):
        START_TAG = "<START>"
        STOP_TAG = "<STOP>"
        X, seq_lengths = self._prepare_sequences(X) # converts tokens into tokenIds
        if y is None:
            return TorchRNNDataset(X, seq_lengths)
        else:
            # These are the changes from a regular classifier. All
            # concern the fact that our labels are sequences of labels.
            self.classes_ = sorted({x for seq in y for x in seq})
            self.n_classes_ = len(self.classes_)
            class2index = dict(zip(self.classes_, range(self.n_classes_)))
            #class2index = dict(zip(self.classes_, range(2,2+self.n_classes_)))
            #class2index[STOP_TAG]=0    # add start and stop tags (note: stop needs to be 0 as that is default for padding in collate_fn)
            #class2index[START_TAG]=1 
            # `y` is a list of tensors of different length. Our Dataset
            # class will turn it into a padding tensor for processing.
            y = [torch.tensor([class2index[label] for label in seq])
                 for seq in y] # converts labels to indices
            return TorchRNNDataset(X, seq_lengths, y)

    def predict_proba(self, X):
        seq_lengths = [len(ex) for ex in X]
        # The base class does the heavy lifting:
        preds = self._predict(X)
        # Trim to the actual sequence lengths:
        preds = [p[: l] for p, l in zip(preds, seq_lengths)]
        # Use `softmax`; the model doesn't do this because the loss
        # function does it internally.
        probs = [torch.softmax(seq, dim=1) for seq in preds]
        return probs

    def predict(self, X):
        probs = self.predict_proba(X)
        return [[self.classes_[i] for i in seq.argmax(axis=1)] for seq in probs] # seq.argmax(axis=1) gives index of col that maximizes softmax prob
        # see difference vs TorchRNNClassifier.predict

    def score(self, X, y):
        preds = self.predict(X)
        flat_preds = [x for seq in preds for x in seq]
        flat_y = [x for seq in y for x in seq]
        return utils.safe_macro_f1(flat_y, flat_preds)
    
    def nClasses(self):
        return len(self.classes_)


In [103]:
class TorchSequenceLabeler_forCRF_1(nn.Module): # no self.hidden_layer or self.classifier_activation as TorchRNNClassifierModel
    def __init__(self, rnn, output_dim):
        print("here021")
        super().__init__()
        self.rnn = rnn
        self.output_dim = output_dim
        if self.rnn.bidirectional:
            self.classifier_dim = self.rnn.hidden_dim * 2
        else:
            self.classifier_dim = self.rnn.hidden_dim
        self.classifier_layer = nn.Linear(
            self.classifier_dim, self.output_dim)

    def forward(self, X, seq_lengths): # X is (noExsInBatch,MaxLen)=(108,117), seq_lengths is the number of tokens in each example in each batch
        # this is the forward method of self.model
        print("here2")
        outputs, state = self.rnn(X, seq_lengths) # X is (batchSize, maxLen of exs in batch); outputs is (noTokensInEx,hiddDim), state is ((batch_size,1,hiddDim),(batch_size,1,hiddDim)) = (finalHiddState,finalCellState) 
        outputs, seq_length = torch.nn.utils.rnn.pad_packed_sequence(
            outputs, batch_first=True) # outputs is (batchSize,MaxLen of examples in batch,hidden_dim); seq_length is noTokenInEx for each ex in batch
        logits = self.classifier_layer(outputs) # this is an FCL from hidden_dim to output_dim (NoLabelClasses)
        # logits are (108,117,12) or (1,11,5) = (batchSize,MaxLen of examples in batch,noLabelClasses) noLabelClasses include Start + End
        # During training, we need to swap the dimensions of logits
        # to accommodate `nn.CrossEntropyLoss`:
        if self.training:
            return logits.transpose(1, 2) # transpose dimensions 1 and 2 w/ each other (3d array) # outputs (108,12,117) or (1,5,11)
        else:
            return logits

In [234]:
# reload vsm module
import torch_rnn_classifier, torch_model_base
import importlib
importlib.reload(torch_model_base)
importlib.reload(torch_rnn_classifier)
from torch_model_base import TorchModelBase
from torch_rnn_classifier import TorchRNNClassifier, TorchRNNModel, TorchRNNDataset

In [239]:
from torchcrf import CRF

class TorchCRFSequenceLabeler_2(TorchRNNClassifier):

    def build_graph(self): # uses this build_graph instead of TorchRNNClassifier.build_graph
        print("here0")
        rnn = TorchRNNModel(
            vocab_size=len(self.vocab),
            embedding=self.embedding,
            use_embedding=self.use_embedding,
            embed_dim=self.embed_dim,
            rnn_cell_class=self.rnn_cell_class,
            hidden_dim=self.hidden_dim,
            bidirectional=self.bidirectional,
            freeze_embedding=self.freeze_embedding)
        self.crf = CRF(self.n_classes_,batch_first=True)
        print("here02")
        model = TorchSequenceLabeler_forCRF_2( # this defines self.model
            rnn=rnn,
            output_dim=self.n_classes_,
            crf=self.crf)
        print("here002")
        self.embed_dim = rnn.embed_dim
        return model

    def build_dataset(self, X, y=None):
        X, seq_lengths = self._prepare_sequences(X) # converts tokens into tokenIds
        if y is None:
            return TorchRNNDataset(X, seq_lengths)
        else:
            # These are the changes from a regular classifier. All
            # concern the fact that our labels are sequences of labels.
            self.classes_ = sorted({x for seq in y for x in seq})
            self.n_classes_ = len(self.classes_)
            class2index = dict(zip(self.classes_, range(self.n_classes_)))
            #class2index = dict(zip(self.classes_, range(2,2+self.n_classes_)))
            #class2index[STOP_TAG]=0    # add start and stop tags (note: stop needs to be 0 as that is default for padding in collate_fn)
            #class2index[START_TAG]=1 
            # `y` is a list of tensors of different length. Our Dataset
            # class will turn it into a padding tensor for processing.
            y = [torch.tensor([class2index[label] for label in seq])
                 for seq in y] # converts labels to indices
            return TorchRNNDataset(X, seq_lengths, y)

    def predict_proba(self, X):
        seq_lengths = [len(ex) for ex in X]
        # The base class does the heavy lifting:
        preds = self._predict(X)
        # Trim to the actual sequence lengths:
        preds = [p[: l] for p, l in zip(preds, seq_lengths)]
        # Use `softmax`; the model doesn't do this because the loss
        # function does it internally.
        probs = [torch.softmax(seq, dim=1) for seq in preds]
        return probs

    def predict(self, X): # for CRF-RNN X are logits from RNN
       # probs = self.predict_proba(X)
       # return [[self.classes_[i] for i in seq.argmax(axis=1)] for seq in probs] # seq.argmax(axis=1) gives index of col that maximizes softmax prob
        seq_lengths = [len(ex) for ex in X]
        preds = self._predict(X)
        # Trim to the actual sequence lengths:
        preds = [p[: l] for p, l in zip(preds, seq_lengths)]        
        mask=self.create_mask(seq_lengths) # creates mask matrix (1s are obs used in CRF; 0s are discarded)  
        print("pred")
        print(X.shape)
        print(mask.shape)
       # tag_seq = self.crf.decode(X,mask=mask) # note: X is (nExs,maxTokLen) and here input must be (nExs,maxTokLen,nDistinctTags)
        # [[self.classes_[i] for i in seq] for seq in tag_seq]
        return 0
        # see difference vs TorchRNNClassifier.predict

    def score(self, X, y):
       # preds = self.predict(X)
       # flat_preds = [x for seq in preds for x in seq]
       # flat_y = [x for seq in y for x in seq]
       # return utils.safe_macro_f1(flat_y, flat_preds)
        seq_lengths = [len(ex) for ex in X]
        mask=self.create_mask(seq_lengths) # creates mask matrix (1s are obs used in CRF; 0s are discarded)
        return self.crf(logits, y, mask=mask)
        
    
    def nClasses(self):
        return len(self.classes_)
    
    def create_mask(self, seq_length):
        maxLen=max(seq_length)
        auxLen=len(seq_length)
        auxOne = torch.ones(maxLen)
        auxZero = torch.zeros(maxLen)
        auxOne_l=[1]*maxLen
        auxZero_l=[0]*maxLen
        auxMatrix=[]
        for i in range(auxLen):
            auxRow=auxOne_l[:seq_length[i]]+auxZero_l[seq_length[i]:]
            auxMatrix.append(auxRow)
        return torch.tensor(auxMatrix,dtype=torch.uint8)  

In [240]:
class TorchSequenceLabeler_forCRF_2(nn.Module): # no self.hidden_layer or self.classifier_activation as TorchRNNClassifierModel
    def __init__(self, rnn, output_dim, crf):
        print("here021")
        super().__init__()
        self.rnn = rnn
        self.output_dim = output_dim
        if self.rnn.bidirectional:
            self.classifier_dim = self.rnn.hidden_dim * 2
        else:
            self.classifier_dim = self.rnn.hidden_dim
        self.classifier_layer = nn.Linear(
            self.classifier_dim, self.output_dim)
        self.crf = crf

    def forward(self, X, seq_lengths): # X is (noExsInBatch,MaxLen)=(108,117), seq_lengths is the number of tokens in each example in each batch
        # this is the forward method of self.model
        print("here2")
        outputs, state = self.rnn(X, seq_lengths) # X is (batchSize, maxLen of exs in batch); outputs is (noTokensInEx,hiddDim), state is ((batch_size,1,hiddDim),(batch_size,1,hiddDim)) = (finalHiddState,finalCellState) 
        outputs, seq_length = torch.nn.utils.rnn.pad_packed_sequence(
            outputs, batch_first=True) # outputs is (batchSize,MaxLen of examples in batch,hidden_dim); seq_length is noTokenInEx for each ex in batch
        logits = self.classifier_layer(outputs) # this is an FCL from hidden_dim to output_dim (NoLabelClasses)
       # print(logits.shape)
        # logits are (108,117,12) or (1,11,5) = (batchSize,MaxLen of examples in batch,noLabelClasses) noLabelClasses include Start + End
        # During training, we need to swap the dimensions of logits
        # to accommodate `nn.CrossEntropyLoss`:
       # if self.training:
       #     return logits.transpose(1, 2) # transpose dimensions 1 and 2 w/ each other (3d array) # outputs (108,12,117) or (1,5,11)
       # else:
       #     return logits
        device = "cuda" if torch.cuda.is_available() else "cpu"
        mask = (self.create_mask(seq_lengths)).to(device, non_blocking=True)
        print("fwd")
        print(logits.shape)
        print(mask.shape)
        #tag_seqs = self.crf.decode(logits, mask=mask) # most likely tag sequences
        return self.crf.forward(logits, mask=mask)
    
    def create_mask(self, seq_length):
        maxLen=max(seq_length)
        auxLen=len(seq_length)
        auxOne = torch.ones(maxLen)
        auxZero = torch.zeros(maxLen)
        auxOne_l=[1]*maxLen
        auxZero_l=[0]*maxLen
        auxMatrix=[]
        for i in range(auxLen):
            auxRow=auxOne_l[:seq_length[i]]+auxZero_l[seq_length[i]:]
            auxMatrix.append(auxRow)
        return torch.tensor(auxMatrix,dtype=torch.uint8)      

In [175]:
# Following converts words to indices and pads sequences
seq_mod1 = TorchCRFSequenceLabeler_1(
    vocab,
    early_stopping=True,
    eta=0.001)

In [ ]:
%time _ = seq_mod1.fit(X_train, y_train)

In [109]:
def create_mask(seq_length):
    maxLen=max(seq_length)
    auxLen=len(seq_length)
    auxOne = torch.ones(maxLen)
    auxZero = torch.zeros(maxLen)
    auxOne_l=[1]*maxLen
    auxZero_l=[0]*maxLen
    auxMatrix=[]
    for i in range(auxLen):
        auxRow=auxOne_l[:seq_length[i]]+auxZero_l[seq_length[i]:]
        auxMatrix.append(auxRow)
    return torch.tensor(auxMatrix,dtype=torch.uint8)
#check:
#out=create_mask(seq_length)
#print(out)
#print(torch.sum(out,dim=1))

#Note: before was doing this but can't use this as not guaranteed that label[STOP]=0
    # a=torch.full_like(y,0,dtype=torch.uint8)
    # b=torch.full_like(y,1,dtype=torch.uint8)
    # mask=torch.where(y==0,a,b) 

In [110]:
########## SAMPLE CRF ON REAL DATA
import torch.optim as optim

torch.manual_seed(1)
dataset = seq_mod1.build_dataset(X_train, y_train) 
dataloader = seq_mod1._build_dataloader(dataset, shuffle=False) 
graph = seq_mod1.build_graph()
num_tags = seq_mod1.nClasses()
model_CRF = CRF(num_tags,batch_first=True)

optimizer = optim.SGD(model_CRF.parameters(), lr=0.01, weight_decay=1e-4)

for batch_num, batch in enumerate(dataloader, start=1):
    x=batch[0]   
    seq_length=batch[1]
    y=batch[2] 
    logits = graph.forward(x,seq_length).transpose(1,2)
    print(logits.shape)
    
    # CRF piece:
    mask=create_mask(seq_length) # creates mask matrix (1s are obs used in CRF; 0s are discarded)
    loss=-model_CRF(logits, y, mask=mask) # in this way minimizing loss means max log likelihood (i.e. we're converting to NLL)
    print(loss)
    loss.backward()
    optimizer.step()
    print(model_CRF.decode(logits,mask=mask))


here0
here01
here02
here021
here2
here21
torch.Size([120, 117, 12])
tensor(16929.6426, grad_fn=<NegBackward>)
[[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6

In [111]:
print(graph)

TorchSequenceLabeler_forCRF_1(
  (rnn): TorchRNNModel(
    (embedding): Embedding(1049, 50)
    (rnn): LSTM(50, 50, batch_first=True)
  )
  (classifier_layer): Linear(in_features=50, out_features=12, bias=True)
)


In [237]:
# Following converts words to indices and pads sequences
seq_mod2 = TorchCRFSequenceLabeler_2(
    vocab,
    early_stopping=True,
    eta=0.001)

In [245]:
%time _ = seq_mod2.fit(X_train, y_train)

here00
here0
here01
here02
here021
here002
batch1
here-model
here2
here21
fwd
torch.Size([108, 117, 12])
torch.Size([108, 117])


TypeError: forward() missing 1 required positional argument: 'tags'

In [244]:
#############################################################
################### I AM WORKING HERE #######################

import torch.optim as optim

torch.manual_seed(1)
dataset = seq_mod2.build_dataset(X_train, y_train) 
dataloader = seq_mod2._build_dataloader(dataset, shuffle=False) 
graph = seq_mod2.build_graph()
num_tags = seq_mod2.nClasses()
#model_CRF = CRF(num_tags,batch_first=True)

#optimizer = optim.SGD(model_CRF.parameters(), lr=0.01, weight_decay=1e-4)

for batch_num, batch in enumerate(dataloader, start=1):
    x=batch[0]   
    seq_length=batch[1]
    y=batch[2] 
  #  print(x.shape)
  #  print(seq_length.shape)
    logits = graph.forward(x,seq_length)
   # print(logits)
    print(seq_mod2.predict(x))
    
    # CRF piece:
   # mask=create_mask(seq_length) # creates mask matrix (1s are obs used in CRF; 0s are discarded)
   # loss=-model_CRF(logits, y, mask=mask) # in this way minimizing loss means max log likelihood (i.e. we're converting to NLL)
   # print(loss)
   # loss.backward()
   # optimizer.step()
   # print(model_CRF.decode(logits,mask=mask))

here0
here01
here02
here021
here002
here2
here21
fwd
torch.Size([120, 117, 12])
torch.Size([120, 117])


TypeError: forward() missing 1 required positional argument: 'tags'

In [188]:
graph = seq_mod2.build_graph()
print(graph)

here0
here01
here02
here021
here002
TorchSequenceLabeler_forCRF_2(
  (rnn): TorchRNNModel(
    (embedding): Embedding(1049, 50)
    (rnn): LSTM(50, 50, batch_first=True)
  )
  (classifier_layer): Linear(in_features=50, out_features=12, bias=True)
  (crf): CRF(num_tags=12)
)


In [503]:
# reload vsm module
import torch_rnn_classifier, torch_model_base
import importlib
importlib.reload(torch_model_base)
importlib.reload(torch_rnn_classifier)
from torch_model_base import TorchModelBase
from torch_rnn_classifier import TorchRNNClassifier, TorchRNNModel, TorchRNNDataset

In [504]:
from torchcrf import CRF
import copy
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import utils

class TorchCRFSequenceLabeler_3(TorchRNNClassifier):

    def __init__(self,             
            vocab,
            hidden_dim=50,
            embedding=None,
            use_embedding=True,
            embed_dim=50,
            rnn_cell_class=nn.LSTM,
            bidirectional=False,
            freeze_embedding=False,
            classifier_activation=nn.ReLU(),
            **base_kwargs):   
        self.vocab = vocab
        self.hidden_dim = hidden_dim
        self.embedding = embedding
        self.use_embedding = use_embedding
        self.embed_dim = embed_dim
        self.rnn_cell_class = rnn_cell_class
        self.bidirectional = bidirectional
        self.freeze_embedding = freeze_embedding
        self.classifier_activation = classifier_activation
        super().__init__(vocab,**base_kwargs)
        self.params += [
            'hidden_dim',
            'embed_dim',
            'embedding',
            'use_embedding',
            'rnn_cell_class',
            'bidirectional',
            'freeze_embedding',
            'classifier_activation']
        self.loss = lambda x:x
        if self.bidirectional:
            self.classifier_dim = self.hidden_dim * 2
        else:
            self.classifier_dim = self.hidden_dim
       # self.classifier_layer = nn.Linear(
       #     self.classifier_dim, self.n_classes_)

       
    def build_graph(self): # uses this build_graph instead of TorchRNNClassifier.build_graph
       # print("here0")
        rnn = TorchRNNModel(
            vocab_size=len(self.vocab),
            embedding=self.embedding,
            use_embedding=self.use_embedding,
            embed_dim=self.embed_dim,
            rnn_cell_class=self.rnn_cell_class,
            hidden_dim=self.hidden_dim,
            bidirectional=self.bidirectional,
            freeze_embedding=self.freeze_embedding)
      #  print("here02")
        model = TorchSequenceLabeler_forCRF_3( # this defines self.model
            rnn=rnn,
            output_dim=self.n_classes_)
      #  print("here002")
        self.embed_dim = rnn.embed_dim
        self.rnn = rnn
        return model

    def build_dataset(self, X, y=None):
        X, seq_lengths = self._prepare_sequences(X) # converts tokens into tokenIds
        if y is None:
            return TorchRNNDataset(X, seq_lengths)
        else:
            # These are the changes from a regular classifier. All
            # concern the fact that our labels are sequences of labels.
            self.classes_ = sorted({x for seq in y for x in seq})
            self.n_classes_ = len(self.classes_)
            class2index = dict(zip(self.classes_, range(self.n_classes_)))
            #class2index = dict(zip(self.classes_, range(2,2+self.n_classes_)))
            #class2index[STOP_TAG]=0    # add start and stop tags (note: stop needs to be 0 as that is default for padding in collate_fn)
            #class2index[START_TAG]=1 
            # `y` is a list of tensors of different length. Our Dataset
            # class will turn it into a padding tensor for processing.
            y = [torch.tensor([class2index[label] for label in seq])
                 for seq in y] # converts labels to indices
            return TorchRNNDataset(X, seq_lengths, y)

    def predict_proba(self, X):
        seq_lengths = [len(ex) for ex in X]
        # The base class does the heavy lifting:
        preds = self._predict(X)
        # Trim to the actual sequence lengths:
        preds = [p[: l] for p, l in zip(preds, seq_lengths)]
        # Use `softmax`; the model doesn't do this because the loss
        # function does it internally.
        probs = [torch.softmax(seq, dim=1) for seq in preds]
        return probs

    def predict(self, X): # for CRF-RNN X are logits from RNN
       # probs = self.predict_proba(X)
       # return [[self.classes_[i] for i in seq.argmax(axis=1)] for seq in probs] # seq.argmax(axis=1) gives index of col that maximizes softmax prob
        seq_lengths = [len(ex) for ex in X]
        preds = self._predict(X)
        # Trim to the actual sequence lengths:
        preds = [p[: l] for p, l in zip(preds, seq_lengths)]        
        mask=self.create_mask(seq_lengths) # creates mask matrix (1s are obs used in CRF; 0s are discarded)  
        print("pred")
        print(X.shape)
        print(mask.shape)
       # tag_seq = self.crf.decode(X,mask=mask) # note: X is (nExs,maxTokLen) and here input must be (nExs,maxTokLen,nDistinctTags)
        # [[self.classes_[i] for i in seq] for seq in tag_seq]
        return 0
        # see difference vs TorchRNNClassifier.predict

    def score(self, X, y):
       # preds = self.predict(X)
       # flat_preds = [x for seq in preds for x in seq]
       # flat_y = [x for seq in y for x in seq]
       # return utils.safe_macro_f1(flat_y, flat_preds)
        device = "cuda" if torch.cuda.is_available() else "cpu"
        seq_lengths = [len(ex) for ex in X]
        mask=self.create_mask(seq_lengths).to(device, non_blocking=True) # creates mask matrix (1s are obs used in CRF; 0s are discarded)
        outputs, state = self.rnn(X, torch.tensor(seq_lengths)) # X is (batchSize, maxLen of exs in batch); outputs is (noTokensInEx,hiddDim), state is ((batch_size,1,hiddDim),(batch_size,1,hiddDim)) = (finalHiddState,finalCellState) 
        outputs, seq_length = torch.nn.utils.rnn.pad_packed_sequence(outputs, batch_first=True) # outputs is (batchSize,MaxLen of examples in batch,hidden_dim); seq_length is noTokenInEx for each ex in batch
        fcl = nn.Linear(self.classifier_dim, self.n_classes_).to(device, non_blocking=True)
        logits = fcl(outputs) # this is an FCL from hidden_dim to output_dim (NoLabelClasses)
        return self.crf(logits, y, mask=mask)
        
    
    def nClasses(self):
        return len(self.classes_)
    
    def create_mask(self, seq_length):
        maxLen=max(seq_length)
        auxLen=len(seq_length)
        auxOne = torch.ones(maxLen)
        auxZero = torch.zeros(maxLen)
        auxOne_l=[1]*maxLen
        auxZero_l=[0]*maxLen
        auxMatrix=[]
        for i in range(auxLen):
            auxRow=auxOne_l[:seq_length[i]]+auxZero_l[seq_length[i]:]
            auxMatrix.append(auxRow)
        return torch.tensor(auxMatrix,dtype=torch.uint8)  

    
    def fit(self, *args):
        """
        Generic optimization method.

        Parameters
        ----------
        *args: list of objects
            We assume that the final element of args give the labels
            and all the preceding elements give the system inputs.
            For regular supervised learning, this is like (X, y), but
            we allow for models that might use multiple data structures
            for their inputs.

        Attributes
        ----------
        model: nn.Module or subclass thereof
            Set by `build_graph`. If `warm_start=True`, then this is
            initialized only by the first call to `fit`.

        optimizer: torch.optimizer.Optimizer
            Set by `build_optimizer`. If `warm_start=True`, then this is
            initialized only by the first call to `fit`.

        errors: list of float
            List of errors. If `warm_start=True`, then this is
            initialized only by the first call to `fit`. Thus, where
            `max_iter=5`, if we call `fit` twice with `warm_start=True`,
            then `errors` will end up with 10 floats in it.

        validation_scores: list
            List of scores. This is filled only if `early_stopping=True`.
            If `warm_start=True`, then this is initialized only by the
            first call to `fit`. Thus, where `max_iter=5`, if we call
            `fit` twice with `warm_start=True`, then `validation_scores`
            will end up with 10 floats in it.

        no_improvement_count: int
            Used to control early stopping and convergence. These values
            are controlled by `_update_no_improvement_count_early_stopping`
            or `_update_no_improvement_count_errors`.  If `warm_start=True`,
            then this is initialized only by the first call to `fit`. Thus,
            in that situation, the values could accumulate across calls to
            `fit`.

        best_error: float
           Used to control convergence. Smaller is assumed to be better.
           If `warm_start=True`, then this is initialized only by the first
           call to `fit`. It will be reset by
           `_update_no_improvement_count_errors` depending on how the
           optimization is proceeding.

        best_score: float
           Used to control early stopping. If `warm_start=True`, then this
           is initialized only by the first call to `fit`. It will be reset
           by `_update_no_improvement_count_early_stopping` depending on how
           the optimization is proceeding. Important: we currently assume
           that larger scores are better. As a result, we will not get the
           correct results for, e.g., a scoring function based in
           `mean_squared_error`. See `self.score` for additional details.

        best_parameters: dict
            This is a PyTorch state dict. It is used if and only if
            `early_stopping=True`. In that case, it is updated whenever
            `best_score` is improved numerically. If the early stopping
            criteria are met, then `self.model` is reset to contain these
            parameters before `fit` exits.

        Returns
        -------
        self

        """
      #  print("here00")
        if self.early_stopping:
            args, dev = self._build_validation_split(
                *args, validation_fraction=self.validation_fraction)

        # Dataset:
        dataset = self.build_dataset(*args)
        dataloader = self._build_dataloader(dataset, shuffle=True)

        # Graph:
        if not self.warm_start or not hasattr(self, "model"):
            self.model = self.build_graph()
            # This device move has to happen before the optimizer is built:
            # https://pytorch.org/docs/master/optim.html#constructing-it
            self.model.to(self.device)
            self.optimizer = self.build_optimizer()
            self.errors = []
            self.validation_scores = []
            self.no_improvement_count = 0
            self.best_error = np.inf
            self.best_score = -np.inf
            self.best_parameters = None

        # Make sure the model is where we want it:
        self.model.to(self.device)

        self.model.train()
        self.optimizer.zero_grad()

        for iteration in range(1, self.max_iter+1):

            epoch_error = 0.0

            for batch_num, batch in enumerate(dataloader, start=1):
               # print("batch"+str(batch_num)) 

               # print(batch)
                batch = [x.to(self.device, non_blocking=True) for x in batch]

                X_batch = batch[: -1] # list w/ 2 els: 1st el is tensor (108xmaxLen) w/ tokens for each example in batch; 2nd el is (108x1) with lengths of each example
                y_batch = batch[-1] # list with each element of this batch (108 el in list) with tensor (maxLen x 1) labels converted to ints and w/ len = maxLen of all example sequences # print(y_batch[0].shape)
               # print(X_batch[1].shape)
               # print(y_batch[0])
               
                batch_preds = self.model(*X_batch) # produces logits outputs of lstm
               # print("batch_preds")
                self.crf = CRF(self.n_classes_,batch_first=True).to(self.device, non_blocking=True)

               # print("here-model2")
                mask = (self.create_mask(X_batch[1])).to(self.device, non_blocking=True)
                #err = self.loss(batch_preds, y_batch) # batch_preds = (108,12,117); y_batch = (108,117)
                err = -self.crf(batch_preds,y_batch,mask=mask)

                if self.gradient_accumulation_steps > 1 and \
                  self.loss.reduction == "mean":
                    err /= self.gradient_accumulation_steps

                err.backward()

                epoch_error += err.item()

                if batch_num % self.gradient_accumulation_steps == 0 or \
                  batch_num == len(dataloader):
                    if self.max_grad_norm is not None:
                        torch.nn.utils.clip_grad_norm_(
                            self.model.parameters(), self.max_grad_norm)
                    self.optimizer.step()
                    self.optimizer.zero_grad()

            # Stopping criteria:

            if self.early_stopping:
                #self._update_no_improvement_count_early_stopping(*dev)
                self._update_no_improvement_count_early_stopping(X_batch[0],y_batch)
                if self.no_improvement_count > self.n_iter_no_change:
                    utils.progress_bar(
                        "Stopping after epoch {}. Validation score did "
                        "not improve by tol={} for more than {} epochs. "
                        "Final error is {}".format(iteration, self.tol,
                            self.n_iter_no_change, epoch_error),
                        verbose=self.display_progress)
                    break

            else:
                self._update_no_improvement_count_errors(epoch_error)
                if self.no_improvement_count > self.n_iter_no_change:
                    utils.progress_bar(
                        "Stopping after epoch {}. Training loss did "
                        "not improve more than tol={}. Final error "
                        "is {}.".format(iteration, self.tol, epoch_error),
                        verbose=self.display_progress)
                    break

            utils.progress_bar(
                "Finished epoch {} of {}; error is {}".format(
                    iteration, self.max_iter, epoch_error),
                verbose=self.display_progress)

        if self.early_stopping:
            self.model.load_state_dict(self.best_parameters)

        return self

In [505]:
class TorchSequenceLabeler_forCRF_3(nn.Module): # no self.hidden_layer or self.classifier_activation as TorchRNNClassifierModel
    def __init__(self, rnn, output_dim):
       # print("here021")
        super().__init__()
        self.rnn = rnn
        self.output_dim = output_dim
        if self.rnn.bidirectional:
            self.classifier_dim = self.rnn.hidden_dim * 2
        else:
            self.classifier_dim = self.rnn.hidden_dim
        self.classifier_layer = nn.Linear(
            self.classifier_dim, self.output_dim)
        

    def forward(self, X, seq_lengths): # X is (noExsInBatch,MaxLen)=(108,117), seq_lengths is the number of tokens in each example in each batch
        # this is the forward method of self.model
       # print("here2")
        outputs, state = self.rnn(X, seq_lengths) # X is (batchSize, maxLen of exs in batch); outputs is (noTokensInEx,hiddDim), state is ((batch_size,1,hiddDim),(batch_size,1,hiddDim)) = (finalHiddState,finalCellState) 
        outputs, seq_length = torch.nn.utils.rnn.pad_packed_sequence(
            outputs, batch_first=True) # outputs is (batchSize,MaxLen of examples in batch,hidden_dim); seq_length is noTokenInEx for each ex in batch
        logits = self.classifier_layer(outputs) # this is an FCL from hidden_dim to output_dim (NoLabelClasses)
       # print(logits.shape)
        # logits are (108,117,12) or (1,11,5) = (batchSize,MaxLen of examples in batch,noLabelClasses) noLabelClasses include Start + End
        return logits
    
    def create_mask(self, seq_length):
        maxLen=max(seq_length)
        auxLen=len(seq_length)
        auxOne = torch.ones(maxLen)
        auxZero = torch.zeros(maxLen)
        auxOne_l=[1]*maxLen
        auxZero_l=[0]*maxLen
        auxMatrix=[]
        for i in range(auxLen):
            auxRow=auxOne_l[:seq_length[i]]+auxZero_l[seq_length[i]:]
            auxMatrix.append(auxRow)
        return torch.tensor(auxMatrix,dtype=torch.uint8)    

In [506]:
# Following converts words to indices and pads sequences
seq_mod3 = TorchCRFSequenceLabeler_3(
    vocab,
    early_stopping=True,
    eta=0.001)

In [425]:
torch.manual_seed(1)
dataset = seq_mod3.build_dataset(X_train, y_train) 
dataloader = seq_mod3._build_dataloader(dataset, shuffle=False) 
graph = seq_mod3.build_graph()
print(graph)

here0
here01
here02
here021
here002
TorchSequenceLabeler_forCRF_3(
  (rnn): TorchRNNModel(
    (embedding): Embedding(1049, 50)
    (rnn): LSTM(50, 50, batch_first=True)
  )
  (classifier_layer): Linear(in_features=50, out_features=12, bias=True)
)


In [507]:
%time _ = seq_mod3.fit(X_train, y_train)

Stopping after epoch 21. Validation score did not improve by tol=1e-05 for more than 10 epochs. Final error is 11815.50390625

Wall time: 4.54 s


In [149]:
########## SAMPLE CRF ON TOY DATA
# this is where I matched my first model score (i.e. log likelihood of crf)
torch.manual_seed(1)
seq_length = 1  # maximum sequence length in a batch
batch_size = 1  # number of samples in the batch
num_tags=2
model = CRF(num_tags,batch_first=True)
#emissions = torch.randn(batch_size, seq_length, num_tags)
#tags = torch.tensor([[0, 2, 3], [1, 4, 1]], dtype=torch.long)  # (batch_size, seq_length)
emissions = torch.randn(1, seq_length, num_tags)

tags = torch.tensor([[1]], dtype=torch.long)  
print(model(emissions, tags))
print(emissions)
print(tags)
print(model.transitions)
print(model.start_transitions)
print(model.end_transitions)

tensor(-0.5731, grad_fn=<SumBackward0>)
tensor([[[-0.4519, -0.1661]]])
tensor([[1]])
Parameter containing:
tensor([[-0.0941,  0.0600],
        [-0.0206,  0.0509]], requires_grad=True)
Parameter containing:
tensor([ 0.0515, -0.0441], requires_grad=True)
Parameter containing:
tensor([-0.0194,  0.0469], requires_grad=True)


In [371]:
########## SAMPLE CRF ON TOY DATA
# add mask vector so as to not to consider padding part of sequences
# e.g. want to mask last zero of 2nd obs
torch.manual_seed(1)
seq_length = 3  # maximum sequence length in a batch
batch_size = 2  # number of samples in the batch
num_tags=5
model = CRF(num_tags,batch_first=True)
emissions = torch.randn(batch_size, seq_length, num_tags)
tags = torch.tensor([[1, 2, 3], [1, 4, 0]], dtype=torch.long)  # (batch_size, seq_length)
mask = torch.tensor([[1, 1, 1], [1, 1, 0]], dtype=torch.uint8) # i.e. mask 3rd token of 2nd example in batch
print(emissions.shape)
print(tags.shape)
print(mask.shape)
# 1.
print(model(emissions, tags, mask=mask)) # model log likelihood
# 2.
print(model.decode(emissions,mask=mask)) # most likely tag sequences
# 3. inference:
tags_test = torch.tensor([[1, 2, 3]], dtype=torch.long)  # (batch_size, seq_length)
print(model.forward(emissions[0].unsqueeze(dim=0),tags_test)) # returns log likelihood of test tag sequence (larger no. means more likely)
# note: need to use torch array w/ same no. of examples as tags_test

torch.Size([2, 3, 5])
torch.Size([2, 3])
torch.Size([2, 3])
tensor(-8.3568, grad_fn=<SumBackward0>)
[[3, 4, 3], [4, 1]]
tensor(-2.7487, grad_fn=<SumBackward0>)


In [377]:
# note: this isn't exactly correct as training examples are shuffled (esp. max len of the smaller 12 ex batch is != 92)
auxMax=0
x_max_idx=108
for i in range(0,min(len(X_train),x_max_idx)):
    if len(X_train[i])>auxMax:
        auxMax=len(X_train[i])
print(auxMax)
auxMax2=0
x_min_idx=109
for i in range(max(0,x_min_idx),len(X_train)):
    if len(X_train[i])>auxMax2:
        auxMax2=len(X_train[i])
print(auxMax2)

117
92


In [107]:
y_pred = seq_mod.predict(X_test)
print(y_test[0])
print(y_pred[0])

['ORT', 'O', 'O', 'STRASSE', 'STRASSE', 'O', 'ORT', 'O', 'O', 'FLAECHE', 'O', 'O', 'IMMO_TYP', 'O', 'O', 'O', 'O', 'QMPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'VERKAEUFER', 'O', 'O', 'O', 'O', 'O', 'GESAMTPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'DATUM_VERTRAG', 'DATUM_VERTRAG', 'O', 'O', 'O', 'O', 'O', 'DATUM_VERBUECHERUNG', 'DATUM_VERBUECHERUNG', 'O']
['KAEUFER', 'KAEUFER', 'O', 'O', 'KAEUFER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'IMMO_TYP', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


In [108]:
labels=seq_mod.classes_
sorted_labels = sorted(
    labels,
    key=lambda name: (name[1:], name[0])
)

In [109]:
# unfold all our data - NOTE: this means we don't care about per sentence results. 
# i.e. each classification is worth same regardless of sentence in which it occurs
y_test_unfold = [y for element in y_test for y in element]
y_pred_unfold = [y for element in y_pred for y in element]

In [126]:
print(y_test_unfold[:10])
print(y_pred_unfold[:10])

['ORT', 'O', 'O', 'STRASSE', 'STRASSE', 'O', 'ORT', 'O', 'O', 'FLAECHE']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


In [82]:
# convert y_test and y_pred into binary formats
#from sklearn.preprocessing import MultiLabelBinarizer

In [110]:
print(classification_report(
    y_test_unfold, y_pred_unfold, labels=sorted_labels, digits=3
))

                     precision    recall  f1-score   support

                  O      0.808     0.888     0.846       643
            KAEUFER      0.070     0.278     0.112        18
DATUM_VERBUECHERUNG      0.000     0.000     0.000        25
      DATUM_VERTRAG      1.000     0.037     0.071        27
         VERKAEUFER      0.333     0.042     0.074        24
   TERRASSENGROESSE      0.000     0.000     0.000         5
        GESAMTPREIS      0.000     0.000     0.000        11
            FLAECHE      0.000     0.000     0.000        15
           IMMO_TYP      0.000     0.000     0.000        19
            QMPREIS      0.000     0.000     0.000        10
                ORT      0.000     0.000     0.000        26
            STRASSE      0.118     0.125     0.121        16

           accuracy                          0.691       839
          macro avg      0.194     0.114     0.102       839
       weighted avg      0.664     0.691     0.657       839



Now try with leading "B-" and "I-"

In [83]:
########## ONLY RUN IF WE WANT TO ADD LEADING "B-" / "I-" TO CLASS LABEL
# now use above code and loop through all items of annot list:
# addLeading=1 for "Yes" (i.e. add leading "B-","I-" to annot); 0 for "No" (i.e. add labels to annot simply as they are)
addLeading = 1

if addLeading == 1:
    for j in range(0,len(annot)):
        a = annot[j]
        # select list of dict of tokens w/ annnotations and add column w/ no. of words to each dict:
        b = a['spans']
        # add noWords to b dict. note: b is list of dicts w/ annotations; tokens not on this list don't have annotations
        if b!=[]: #i.e. only try to add annotations to tokens if there are annotations to begin with
            #print(b)
            for i in range(0,len(annot[j]['tokens'])):
                    # now break-up label into 1st occurrence (leading "B-") and subsequent occurrences (leading "I-") (only for non "O"'s)
                    if annot[j]['tokens'][i]['label'] != "O":
                        if i==0:
                            annot[j]['tokens'][i]['label'] = "B-" + annot[j]['tokens'][i]['label']
                        else: 
                            if annot[j]['tokens'][i]['label'] == annot[j]['tokens'][i-1]['label'][2:]: # need to remove the leading "B-" that we had already been added to c[i-1]
                                annot[j]['tokens'][i]['label'] = "I-" + annot[j]['tokens'][i]['label']
                            else:
                                annot[j]['tokens'][i]['label'] = "B-" + annot[j]['tokens'][i]['label'] 

In [84]:
# now get data into format that TorchRNN expects:
X=[] 
y=[]
for j in range(0,len(annot)):
    a = annot[j]['tokens']
    auxX = []
    auxy = []
    if annot[j]['spans']!=[]: # are there annot for this example?
        for i in range(0,len(a)):
            #token_element = (a[i]['text'],a[i]['label'])
            auxX.append(a[i]['text'])
            auxy.append(a[i]['label'])
        X.append(auxX)
        y.append(auxy)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
X_train, X_test, y_train, y_test = X[:120], X[120:], y[:120], y[120:]
vocab = sorted({w for seq in X_train for w in seq}) + ["$UNK"]

In [89]:
print(X_train[0])

['DORNBIRN', 'In', 'der', 'Schulgasse', 'in', 'Dornbirn', 'hat', 'eine', '71,93', 'Quadratmeter', 'große', 'Wohnung', 'für', 'einen', 'Quadratmeterpreis', 'von', '5533,71', 'Euro', 'den', 'Besitzer', 'gewechselt', '.', 'Dieser', 'beinhaltet', 'auch', 'einen', 'Pkw-Abstellplatz', '.', 'Käufer', 'der', 'Wohnung', 'mit', '9,86', 'Quadratmetern', 'Terrasse', 'ist', 'die', 'ValLiLean', 'Beteiligungs-', 'und', 'Immobilienverwaltungs', 'GmbH', 'Beim', 'Verkäufer', 'handelt', 'es', 'sich', 'um', 'die', 'Karrenblick', 'Projekt', 'GmbH', ' ', 'Der', 'Kaufpreis', 'liegt', 'bei', '398.040', 'Euro', '.', 'Unterzeichnet', 'wurde', 'der', 'Kaufvertrag', 'am', '18.', 'September', '.', 'Die', 'Verbücherung', 'datiert', 'mit', 'Oktober', '2020', '.', '.', '.']


In [85]:
%time _ = seq_mod.fit(X_train, y_train)
y_pred = seq_mod.predict(X_test)
print(y_test[0])
print(y_pred[0])

Stopping after epoch 35. Validation score did not improve by tol=1e-05 for more than 10 epochs. Final error is 2.249159574508667

Wall time: 1.78 s
['B-ORT', 'O', 'O', 'B-STRASSE', 'I-STRASSE', 'O', 'B-ORT', 'O', 'O', 'B-FLAECHE', 'O', 'O', 'B-IMMO_TYP', 'O', 'O', 'O', 'O', 'B-QMPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-VERKAEUFER', 'O', 'O', 'O', 'O', 'O', 'B-GESAMTPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-DATUM_VERTRAG', 'I-DATUM_VERTRAG', 'O', 'O', 'O', 'O', 'O', 'B-DATUM_VERBUECHERUNG', 'I-DATUM_VERBUECHERUNG', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


In [90]:
labels=seq_mod.classes_
sorted_labels = sorted(
    labels,
    key=lambda name: (name[1:], name[0])
)

In [91]:
# unfold all our data - NOTE: this means we don't care about per sentence results. 
# i.e. each classification is worth same regardless of sentence in which it occurs
y_test_unfold = [y for element in y_test for y in element]
y_pred_unfold = [y for element in y_pred for y in element]

In [92]:
print(classification_report(
    y_test_unfold, y_pred_unfold, labels=sorted_labels, digits=3
))

                       precision    recall  f1-score   support

                    O      0.773     0.988     0.867       643
B-DATUM_VERBUECHERUNG      0.000     0.000     0.000        13
I-DATUM_VERBUECHERUNG      0.000     0.000     0.000        12
      B-DATUM_VERTRAG      0.000     0.000     0.000        13
      I-DATUM_VERTRAG      0.000     0.000     0.000        14
            B-FLAECHE      0.000     0.000     0.000        15
            I-FLAECHE      0.000     0.000     0.000         0
        B-GESAMTPREIS      0.000     0.000     0.000        11
        I-GESAMTPREIS      0.000     0.000     0.000         0
           B-IMMO_TYP      0.000     0.000     0.000        19
           I-IMMO_TYP      0.000     0.000     0.000         0
            B-KAEUFER      0.000     0.000     0.000        10
            I-KAEUFER      0.000     0.000     0.000         8
                B-ORT      0.300     0.115     0.167        26
            B-QMPREIS      0.000     0.000     0.000  

C:\Users\vasco\anaconda3\envs\xcs224u\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Remove "B-" and "I-" (in case they are present in labels)

In [119]:
for j in range(0,len(annot)):
    a = annot[j]
    b = a['spans']
    if b!=[]: #i.e. only try to add annotations to tokens if there are annotations to begin with
        for i in range(0,len(annot[j]['tokens'])):
                if annot[j]['tokens'][i]['label'] != "O":
                    if annot[j]['tokens'][i]['label'][:2]=="B-" or annot[j]['tokens'][i]['label'][:2]=="I-":
                        annot[j]['tokens'][i]['label']=annot[j]['tokens'][i]['label'][2:]

Try bi-directional LSTM

In [149]:
seq_mod = TorchRNNSequenceLabeler(
    vocab,
    early_stopping=True,
    eta=0.001,
    bidirectional=True)

In [132]:
print(y_train[0])

['ORT', 'O', 'O', 'STRASSE', 'O', 'ORT', 'O', 'O', 'FLAECHE', 'O', 'O', 'IMMO_TYP', 'O', 'O', 'O', 'O', 'QMPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'TERRASSENGROESSE', 'O', 'O', 'O', 'O', 'KAEUFER', 'KAEUFER', 'KAEUFER', 'KAEUFER', 'KAEUFER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'VERKAEUFER', 'VERKAEUFER', 'VERKAEUFER', 'O', 'O', 'O', 'O', 'O', 'GESAMTPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'DATUM_VERTRAG', 'DATUM_VERTRAG', 'O', 'O', 'O', 'O', 'O', 'DATUM_VERBUECHERUNG', 'DATUM_VERBUECHERUNG', 'O', 'O', 'O']


In [150]:
%time _ = seq_mod.fit(X_train, y_train)

None


Stopping after epoch 18. Validation score did not improve by tol=1e-05 for more than 10 epochs. Final error is 2.1157665252685547

Wall time: 2.12 s


In [123]:
y_pred = seq_mod.predict(X_test)
print(y_test[0])
print(y_pred[0])

labels=seq_mod.classes_
sorted_labels = sorted(
    labels,
    key=lambda name: (name[1:], name[0])
)

# unfold all our data - NOTE: this means we don't care about per sentence results. 
# i.e. each classification is worth same regardless of sentence in which it occurs
y_test_unfold = [y for element in y_test for y in element]
y_pred_unfold = [y for element in y_pred for y in element]

print(classification_report(
    y_test_unfold, y_pred_unfold, labels=sorted_labels, digits=3
))

['ORT', 'O', 'O', 'STRASSE', 'STRASSE', 'O', 'ORT', 'O', 'O', 'FLAECHE', 'O', 'O', 'IMMO_TYP', 'O', 'O', 'O', 'O', 'QMPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'VERKAEUFER', 'O', 'O', 'O', 'O', 'O', 'GESAMTPREIS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'DATUM_VERTRAG', 'DATUM_VERTRAG', 'O', 'O', 'O', 'O', 'O', 'DATUM_VERBUECHERUNG', 'DATUM_VERBUECHERUNG', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'IMMO_TYP', 'O', 'O', 'TERRASSENGROESSE', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'TERRASSENGROESSE', 'TERRASSENGROESSE', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
                     precision    recall  f1-score   support

                  O      0.760     0.893     0.821       643
            KAEUFER      0.000     0.000     0.000        18
DATUM_VERBUECHERUN